# База данных если in_memory: false
database:
  in_memory: false
  host: localhost
  port: 5433
  name: calendar_db
  login: postgres
  password: postgress

# Логгер
logger:
  enabled: true
  level: info

